
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/Themeprovider";


import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AttendEase",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
         
          {children}

          </ThemeProvider>
          <script src="https://cdn.lordicon.com/lordicon.js"></script>
        </body>
      </html>
    </ClerkProvider>
  )
}
